In [7]:
import pandas as pd
import datetime

In [10]:
def get_covid_data_jhu(dt_ini, dt_fim, us_columns = True, country = None):
    
    date_range = pd.date_range(start = dt_ini, end = dt_fim).to_list()
    string_range = [str(d.date().strftime("%m-%d-%Y")) for d in date_range]
    
    full_data_list = []
    for dat in string_range:
        url = f"https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/{dat}.csv"
        current_data = pd.read_csv(url)
        full_data_list.append(current_data)
    
    full_df = pd.concat(full_data_list)
    
    if country:
        full_df = full_df[full_df['Country_Region'].isin(country)]
        
    if not us_columns:
        full_df.drop(full_df.columns[0:3], axis = 1, inplace = True)
        
    return full_df

In [15]:
# Examples
print(
        get_covid_data_jhu("2020-05-24", "2020-05-27", us_columns = True, country = ['Brazil'])
        )

      FIPS Admin2  Province_State Country_Region          Last_Update  \
3009   NaN    NaN            Acre         Brazil  2020-05-25 02:32:44
3011   NaN    NaN         Alagoas         Brazil  2020-05-25 02:32:44
3013   NaN    NaN           Amapa         Brazil  2020-05-25 02:32:44
3014   NaN    NaN        Amazonas         Brazil  2020-05-25 02:32:44
3028   NaN    NaN           Bahia         Brazil  2020-05-25 02:32:44
...    ...    ...             ...            ...                  ...
3193   NaN    NaN  Santa Catarina         Brazil  2020-05-28 02:32:31
3194   NaN    NaN       Sao Paulo         Brazil  2020-05-28 02:32:31
3198   NaN    NaN         Sergipe         Brazil  2020-05-28 02:32:31
3218   NaN    NaN       Tocantins         Brazil  2020-05-28 02:32:31
3222   NaN    NaN         Unknown         Brazil  2020-05-28 02:32:31

          Lat    Long_  Confirmed  Deaths  Recovered  Active  \
3009  -9.0238 -70.8120       4160      92          0    4068
3011  -9.5713 -36.7820       6214     316          0    5898
3013   0.9020 -52.0030       6353     163          0    6190
3014  -3.4168 -65.8561      29867    1758          0   28109
3028 -12.5797 -41.7007      13899     460          0   13439
...       ...      ...        ...     ...        ...     ...
3193 -27.2423 -50.2189       7372     126          0    7246
3194 -23.5505 -46.6333      89483    6712          0   82771
3198 -10.5741 -37.3857       5912     127          0    5785
3218 -10.1753 -48.2982       3023      65          0    2958
3222      NaN      NaN          0       0     166647 -166647

                Combined_Key
3009            Acre, Brazil
3011         Alagoas, Brazil
3013           Amapa, Brazil
3014        Amazonas, Brazil
3028           Bahia, Brazil
...                      ...
3193  Santa Catarina, Brazil
3194       Sao Paulo, Brazil
3198         Sergipe, Brazil
3218       Tocantins, Brazil
3222         Unknown, Brazil

[112 rows x 12 columns]

In [14]:
get_covid_data_jhu

In [26]:
get_covid_data_jhu("2020-05-24", "2020-05-27", us_columns = True, country = ['Brazil'])

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
3009,NaN,NaN,Acre,Brazil,2020-05-25 02:32:44,-9.0238,-70.8120,4160,92,0,4068,"Acre, Brazil"
3011,NaN,NaN,Alagoas,Brazil,2020-05-25 02:32:44,-9.5713,-36.7820,6214,316,0,5898,"Alagoas, Brazil"
3013,NaN,NaN,Amapa,Brazil,2020-05-25 02:32:44,0.9020,-52.0030,6353,163,0,6190,"Amapa, Brazil"
3014,NaN,NaN,Amazonas,Brazil,2020-05-25 02:32:44,-3.4168,-65.8561,29867,1758,0,28109,"Amazonas, Brazil"
3028,NaN,NaN,Bahia,Brazil,2020-05-25 02:32:44,-12.5797,-41.7007,13899,460,0,13439,"Bahia, Brazil"
...,...,...,...,...,...,...,...,...,...,...,...,...
3193,NaN,NaN,Santa Catarina,Brazil,2020-05-28 02:32:31,-27.2423,-50.2189,7372,126,0,7246,"Santa Catarina, Brazil"
3194,NaN,NaN,Sao Paulo,Brazil,2020-05-28 02:32:31,-23.5505,-46.6333,89483,6712,0,82771,"Sao Paulo, Brazil"
3198,NaN,NaN,Sergipe,Brazil,2020-05-28 02:32:31,-10.5741,-37.3857,5912,127,0,5785,"Sergipe, Brazil"
3218,NaN,NaN,Tocantins,Brazil,2020-05-28 02:32:31,-10.1753,-48.2982,3023,65,0,2958,"Tocantins, Brazil"
3222,NaN,NaN,Unknown,Brazil,2020-05-28 02:32:31,NaN,NaN,0,0,166647,-166647,"Unknown, Brazil"

In [30]:
df = get_covid_data_jhu("2020-05-24", "2020-05-27", us_columns = True, country = ['Brazil'])
df.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
3009,NaN,NaN,Acre,Brazil,2020-05-25 02:32:44,-9.0238,-70.8120,4160,92,0,4068,"Acre, Brazil"
3011,NaN,NaN,Alagoas,Brazil,2020-05-25 02:32:44,-9.5713,-36.7820,6214,316,0,5898,"Alagoas, Brazil"
3013,NaN,NaN,Amapa,Brazil,2020-05-25 02:32:44,0.9020,-52.0030,6353,163,0,6190,"Amapa, Brazil"
3014,NaN,NaN,Amazonas,Brazil,2020-05-25 02:32:44,-3.4168,-65.8561,29867,1758,0,28109,"Amazonas, Brazil"
3028,NaN,NaN,Bahia,Brazil,2020-05-25 02:32:44,-12.5797,-41.7007,13899,460,0,13439,"Bahia, Brazil"